#!/bin/bash

token=$1
verify_url=$(cat /data/open_tv_token_url.txt |head -n1)
if [ -n "$verify_url" ]; then
	curl -s --retry 2 --max-time 5 $verify_url -X POST -H "User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36" -H "Rererer:https://www.aliyundrive.com/" -H "Content-Type:application/json" -d '{"refresh_token":"'$token'", "grant_type": "refresh_token"}' | sed 's/,/\n/g' | grep refresh_token | cut -d \: -f2 | cut -f2 -d\"
fi
