#!/bin/bash                                                   
                                                                          
#OIFS="$IFS"                                                      
#IFS="${IFS}&"                                                    
#set $QUERY_STRING                                                
#Args="$*"                                                        
#IFS="$OIFS"                                                              
              
TYPE=${QUERY_STRING#*type=}
TYPE=${TYPE%%&*} 
type=${TYPE//+/ }                                                            
URL=${QUERY_STRING#*url=}                                                 
URL=${URL%%&*}                                                            
URL=${URL//+/ }                                                           
BOX=${QUERY_STRING#*box=}                                                 
BOX=${BOX%%&*}                                                            
BOX=${BOX//+/ }                                                           
                                                                          
function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }            
                                                                          
echo "Content-type: text/html;charset=UTF-8"                              
echo ""                                                                   
                                                                          
cat header.html                                                                

echo "<div>"
echo "<ul>"

box=$(urldecode $BOX)
box=${box// /\.\*} 
keyword_len=${#box}

if [[ "$keyword_len"  -gt 40 ]]; then
	echo "<h2>输入的搜索关键词太长了，请重新输入</h2>" "<p>"
	echo "</ul></div></body></html>"  
	exit 0
elif [[ "$keyword_len"  -le 1 ]]; then
        echo "<h2>输入的搜索关键词太短了，请重新输入</h2>" "<p>" 
        echo "</ul></div></body></html>"
	exit 0
fi

if [ $type = "video" ]; then
	indexfile='/index/index.video.txt'
elif [ $type = "music" ]; then
	indexfile='/index/index.music.txt'
elif [ $type = "ebook" ]; then
        indexfile='/index/index.book.txt'
else
	indexfile='/index/index.txt'
fi

#echo -e `/bin/grep -i -E $box /index.txt|sed 's/ /%20/g' |sed 's/^\.\///g'| sed "s/\(.*\)/<li><a href=$host\/&>&<\/a><br><\/li>/g"`
echo -e `/bin/grep -i $box $indexfile|cut -f1 -d#|sed 's/^\.\///g'|awk -v host=$host '{after=$0;before=$0;gsub(/ /,"%20",$after);print "<a href=/"$after">"before"</a><br></li>"}'`

echo "</ul></div></body></html>"
exit 0
