#!/bin/bash                                                   
                                                                          
#OIFS="$IFS"                                                      
#IFS="${IFS}&"                                                    
#set $QUERY_STRING                                                
#Args="$*"                                                        
#IFS="$OIFS"                                                              
              
TYPE=${QUERY_STRING#*type=}
TYPE=${TYPE%%&*} 
type=${TYPE//+/ }                                                            
URL=${QUERY_STRING#*url=}                                                 
URL=${URL%%&*}                                                            
URL=${URL//+/ }                                                           
BOX=${QUERY_STRING#*box=}                                                 
BOX=${BOX%%&*}                                                            
BOX=${BOX//+/ }                                                           
FILTER=${QUERY_STRING#*filter=}
FILTER=${FILTER%%&*}           
FILTER=${FILTER//+/ }          
NUM=${QUERY_STRING#*num=}      
NUM=${NUM%%&*}                 
NUM=${NUM//+/ }
CAT=${QUERY_STRING#*cat=}
CAT=${CAT%%&*}
CAT=${CAT//+/ }
                                                                          
function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }            
                                                                          
echo "Content-type: text/html;charset=UTF-8"                              
echo ""                                                                   
                                                                          
cat header.html                                                                

echo "<div>"
echo "<ul>"

box=$(urldecode $BOX)
box=${box// /\.\*} 
keyword_len=${#box}
cat=$(urldecode $CAT)
keyword_cat=${#cat}

if [[ "$keyword_cat"  -gt 1 ]]; then
        if [ $NUM ]; then
		echo -e `cat /index/index.$cat.txt|shuf -n $NUM |sed 's/^\.\///g'|awk -v host=$host '{after=$0;before=$0;gsub(/ /,"%20",$after);print "<a href=/"$after">"before"</a><br></li>"}'`
	else
        	echo -e `cat /index/index.$cat.txt|sed 's/^\.\///g'|awk -v host=$host '{after=$0;before=$0;gsub(/ /,"%20",$after);print "<a href=/"$after">"before"</a><br></li>"}'`
	fi
fi

if [[ "$keyword_len"  -gt 40 ]]; then
	echo "<h2>输入的搜索关键词太长了，请重新输入</h2>" "<p>"
	echo "</ul></div></body></html>"  
	exit 0
elif [[ "$keyword_len"  -le 1 ]]; then
        echo "<h2>输入的搜索关键词太短了，请重新输入</h2>" "<p>" 
        echo "</ul></div></body></html>"
	exit 0
fi

if [ $type = "video" ]; then
	indexfile='/index/index.video.txt'
elif [ $type = "music" ]; then
	indexfile='/index/index.music.txt'
elif [ $type = "ebook" ]; then
        indexfile='/index/index.book.txt'
elif [ $type = "daily" ]; then
        indexfile='/index/index.daily.txt'
else
	indexfile='/index/index.txt'
fi

#echo -e `/bin/grep -i -E $box /index.txt|sed 's/ /%20/g' |sed 's/^\.\///g'| sed "s/\(.*\)/<li><a href=$host\/&>&<\/a><br><\/li>/g"`
if [ $FILTER = "last" ]; then
	echo -e `tail -n$NUM $indexfile|grep .|tac|sed 's/^\.\///g'|awk -v host=$host '{after=$0;before=$0;gsub(/ /,"%20",$after);print "<a href=/"$after">"before"</a><br></li>"}'`
elif [ $NUM -gt 0 ]; then
	echo -e `/bin/grep -i $box $indexfile|shuf -n $NUM |sed 's/^\.\///g'|awk -v host=$host '{after=$0;before=$0;gsub(/ /,"%20",$after);print "<a href=/"$after">"before"</a><br></li>"}'`
else
	echo -e `/bin/grep -i $box $indexfile|sed 's/^\.\///g'|awk -v host=$host '{after=$0;before=$0;gsub(/ /,"%20",$after);print "<a href=/"$after">"before"</a><br></li>"}'`
fi

echo "</ul></div></body></html>"
exit 0
