#!/bin/bash

init() {
    if [ ! -d /index/bin ]; then
        mkdir -p /index/bin
        cp -r /bin/* /index/bin/ 2>/dev/null
    fi
    
    if [ ! -d /index/lib ]; then
        mkdir -p /index/lib
        cp -r /lib/* /index/lib/ 2>/dev/null
    fi
    
    if [ ! -d /index/usr/bin ]; then
        mkdir -p /index/usr/bin
        cp -r /usr/bin/* /index/usr/bin/ 2>/dev/null
    fi
    
    if [ ! -d /index/usr/lib ]; then
        mkdir -p /index/usr/lib
        cp -r /usr/lib/* /index/usr/lib/ 2>/dev/null
    fi
}

check() {
    if [ "$POST_DATA"x == "echo ok"x ] || [ "$POST_DATA"x == "echo ok;date +%Y"x ];then
        return 0;
    fi
    
    if curl -s 'http://127.0.0.1/api/fs/list' -H "authorization: $HTTP_AUTHORIZATION" -d '{"path":"/"}' | grep -q "\"code\":200"; then
        return 0
    elif curl -s 'http://127.0.0.1:5678/api/fs/list' -H "authorization: $HTTP_AUTHORIZATION" -d '{"path":"/"}' | grep -q "\"code\":200"; then
        return 0
    elif curl -s 'http://127.0.0.1/api/fs/list' -d '{"path":"/"}' | grep -q "\"code\":200"; then
        return 0
    elif curl -s 'http://127.0.0.1:5678/api/fs/list' -d '{"path":"/"}' | grep -q "\"code\":200"; then
        return 0
    else
        echo "Status: 403 Forbidden"
        echo "Content-type: text/html"
        echo ""
        echo "403 Forbidden"
        exit 0
    fi
}

if [ "$REQUEST_METHOD" = "POST" ] && [ -n "$CONTENT_LENGTH" ]; then
    POST_DATA=$(dd bs="$CONTENT_LENGTH" count=1 status=none)
fi

init
check

echo "Content-type: text/plain;charset=UTF-8"
echo ""

chroot /index sh -c "$POST_DATA"

exit 0
