#!/bin/bash                                                   
                                                                          
#OIFS="$IFS"                                                      
#IFS="${IFS}&"                                                    
#set $QUERY_STRING                                                
#Args="$*"                                                        
#IFS="$OIFS"                                                              
              
TYPE=${QUERY_STRING#*type=}
TYPE=${TYPE%%&*} 
type=${TYPE//+/ }                                                            
URL=${QUERY_STRING#*url=}                                                 
URL=${URL%%&*}                                                            
URL=${URL//+/ }                                                           
BOX=${QUERY_STRING#*box=}                                                 
BOX=${BOX%%&*}                                                            
BOX=${BOX//+/ }                                                           
FILTER=${QUERY_STRING#*filter=}
FILTER=${FILTER%%&*}           
FILTER=${FILTER//+/ }          
NUM=${QUERY_STRING#*num=}      
NUM=${NUM%%&*}                 
NUM=${NUM//+/ }
CAT=${QUERY_STRING#*cat=}
CAT=${CAT%%&*}
CAT=${CAT//+/ }
                                                                          
function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }            
                                                                          
echo "Content-type: text/html;charset=UTF-8"                              
echo ""                                                                   
                                                                          
cat header.html                                                                

echo "<div>"
echo "<ul style=display:flex;flex-direction:row;flex-wrap:wrap;align-content: space-between;>"

box=$(urldecode $BOX)
box=${box// /\.\*} 
keyword_len=${#box}
cat=$(urldecode $CAT)
keyword_cat=${#cat}

if [[ "$keyword_cat"  -gt 1 ]]; then
	indexfile="/index/index.$cat.txt"
else
	indexfile="/index/index.daily.txt"
fi

if [[ "$keyword_len"  -gt 40 ]]; then
	echo "<h2>输入的搜索关键词太长了，请重新输入</h2>" "<p>"
	echo "</ul></div></body></html>"  
	exit 0
elif [[ "$keyword_len"  -le 1 ]]; then
        echo "<h2>输入的搜索关键词太短了，请重新输入</h2>" "<p>" 
        echo "</ul></div></body></html>"
	exit 0
fi

if [ $FILTER = "last" ]; then
	if [ $cat = "daily" ]; then
		echo -e `tail -n$NUM $indexfile|grep .|tac|sed 's/^\.\///g'|awk -v host=$host 'BEGIN{FS="#"} {after=$1;before=$1;gsub(/ /,"%20",$after);gsub(/%20/," ",$2);if ($5!="") print "<figure><a href=/"$1"><img src="$5" width=250></a><figcaption>豆瓣评分： "$4"<br><a href="$1">"$2"</a></figcaption></figure>"}'`
	else 
		echo -e `shuf -n $NUM $indexfile|grep .|sed 's/^\.\///g'|awk -v host=$host 'BEGIN{FS="#"} {after=$1;before=$1;gsub(/ /,"%20",$after);gsub(/%20/," ",$2);if ($5!="") print "<figure><a href=/"$1"><img src="$5" width=250></a><figcaption>豆瓣评分： "$4"<br><a href="$1">"$2"</a></figcaption></figure>"}'`
	fi
else
	echo -e `/bin/grep -i $box $indexfile|sed 's/^\.\///g'|awk -v host=$host '{after=$0;before=$0;gsub(/ /,"%20",$after);print "<a href=/"$after">"before"</a><br></li>"}'`
fi

echo "</ul></div></body></html>"
exit 0
