name: get-xiaoya-src

on:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: xiaoyaliu/alist:latest
    steps:
      - name: Obtain Latest Git ONLY within container for checkout
        run: apk add git --update-cache
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory /__w/xiaoya-src/xiaoya-src
          find / -maxdepth 1 -type f -exec gzexe -d {} \;
          find / -maxdepth 1 -type f -exec cp {} . \; 
          unzip /var/lib/data.zip -d /var/lib/data
          find /var/lib/data -maxdepth 1 -type f -exec gzexe -d {} \;
          cp -r /var/lib/data .
          ls -al

      - uses: stefanzweifel/git-auto-commit-action@v5